# Generated by Django 3.1.1 on 2020-11-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20201124_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='text',
            new_name='name',
        ),
    ]
